---
site_name: Scrapli Replay
site_url: https://github.com/scrapli/scrapli_replay
site_description: "Scrapli Replay: Tools to enable easy testing of scrapli programs"
site_author: Carl Montanari

repo_name: scrapli/scrapli_replay
repo_url: https://github.com/scrapli/scrapli_replay
edit_uri: ''

theme:
    name: material
    palette:
      primary: 'black'
      accent: 'teal'
    icon:
      repo: fontawesome/brands/github-alt

nav:
  - Scrapli Replay: index.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Project Details: user_guide/project_details.md
      - Versioning: user_guide/versioning.md
      - Installation: user_guide/installation.md
      - Basic Usage: user_guide/basic_usage.md
  - Changelog: changelog.md
  - More Scrapli:
    - Scrapli: more_scrapli/scrapli.md
    - Nornir Scrapli: more_scrapli/nornir_scrapli.md
    - Scrapli Community: more_scrapli/scrapli_community.md
    - Scrapli Netconf: more_scrapli/scrapli_netconf.md
    - Scrapli Stubs: more_scrapli/scrapli_stubs.md
  - Other:
    - Contributing: about/contributing.md
    - Code of Conduct: about/code_of_conduct.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - codehilite
    - extra
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: 'https://github.com/carlmontanari/scrapli'
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/carlrmontanari'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/carl-montanari-47888931/'
        - icon: fontawesome/solid/globe
          link: 'https://montanari.io'

plugins:
    - search
