[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "scrapli_replay"
dynamic = [
    "version",
    "dependencies",
    "optional-dependencies",
]
description = "Tools to enable easy testing of scrapli programs"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
authors = [
    { name = "Carl Montanari", email = "carl.r.montanari@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = [
    "arista",
    "automation",
    "cisco",
    "eos",
    "iosxe",
    "iosxr",
    "juniper",
    "junos",
    "netconf",
    "network",
    "nxos",
    "ssh",
    "telnet",
]

[project.urls]
Homepage = "https://github.com/scrapli/scrapli_replay"
Changelog = "https://scrapli.github.io/scrapli_replay/changelog/"
Docs = "https://scrapli.github.io/scrapli_replay/"

[project.entry-points."pytest11"]
scrapli_replay = "scrapli_replay.replay.pytest_scrapli_replay"

[tool.setuptools.dynamic]
version = { attr = "scrapli_replay.__version__" }
dependencies = { file = "requirements.txt" }
optional-dependencies.dev = { file = [
    "requirements-dev.txt",
] }
optional-dependencies.docs = { file = "requirements-docs.txt" }

[tool.setuptools.package-data]
scrapli_replay = [
    "py.typed"
]

[tool.coverage.run]
source = [
    "scrapli_replay/"
]

[tool.coverage.report]
sort = "cover"

[tool.black]
line-length = 100
target-version = [
    "py311",
]
[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pylama]
linters = "mccabe,pycodestyle,pylint"
skip = ".nox/*,.private/*,build/*,docs/*,private/*,site/*,tests/*,venv/*"

[tool.pylama.pycodestyle]
max_line_length = 100

[tool.pylama.pylint]
rcfile = ".pylintrc"

[tool.pydocstyle]
match-dir = "^scrapli_replay/*"
ignore = "D101,D202,D203,D212,D400,D406,D407,D408,D409,D415"
# D101: missing docstring in public class
# D202: No blank lines allowed after function docstring
# D203: 1 blank line required before class docstring
# D212: Multi-line docstring summary should start at the first line
# D400: First line should end with a period
# D406: Section name should end with a newline
# D407: Missing dashed underline after section
# D408: Section underline should be in the line following the sections name
# D409: Section underline should match the length of its name
# D415: first line should end with a period, question mark, or exclamation point

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_first_party = "scrapli"
known_third_party = "asyncssh,pytest"

[tool.mypy]
python_version = "3.10"
pretty = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true

